import React from 'react';
import { Link } from 'react-router-dom';
import Layout from '../components/Layout';
import '../styles/style.css';

export default function Privacy() {
  return (
    <Layout>
      <div className="page_footer">
        <div className="content">
          <div className="full_width">
            <section>
              <span class="push">
                <span class="circle_border">
                  <span class="circle">
                    <img loading="lazy" src="https://cdn.nichesites.pikoya.com/general/images/alarm" title="Alarm" alt="Roblox Strategy Hub: Stats, Videos &amp; Power Tips" class="mobile" />
                  </span>
                </span>
              </span>
              <h2>Privacy Policy</h2>
              <span className="text">
                <p>Effective date: September 16, 2018</p>

                <p>Pikoya (&quot;us&quot;, &quot;we&quot;, or &quot;our&quot;) operates the www.robloxgo.com website (hereinafter referred to as the &quot;Service&quot;).</p>
                <p>This page informs you of our policies regarding the collection, use and disclosure of personal data when you use our Service and the choices you have associated with that data.</p>
                <p>We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from <Link to="/terms">https://www.robloxgo.com/terms</Link></p>

                <h2>Definitions</h2>
                <ul>
                  <li><p><strong>Service</strong></p><p>Service is the www.robloxgo.com website operated by Pikoya</p></li>
                  <li><p><strong>Personal Data</strong></p><p>Personal Data means data about a living individual who can be identified from those data.</p></li>
                  <li><p><strong>Usage Data</strong></p><p>Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself.</p></li>
                  <li><p><strong>Cookies</strong></p><p>Cookies are small files stored on your device.</p></li>
                  <li><p><strong>Data Controller</strong></p><p>Data Controller means the natural or legal person who determines the purposes and manner of processing personal information.</p></li>
                  <li><p><strong>Data Processors</strong></p><p>Data Processor means any natural or legal person who processes the data on behalf of the Data Controller.</p></li>
                  <li><p><strong>Data Subject</strong></p><p>Data Subject is any living individual who is using our Service and is the subject of Personal Data.</p></li>
                </ul>

                <h2>Information Collection and Use</h2>
                <p>We collect several different types of information for various purposes to provide and improve our Service to you.</p>
                <h3>Types of Data Collected</h3>
                <h4>Personal Data</h4>
                <p>While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include email address, first name and last name, cookies and usage data.</p>
                <p>We may use your Personal Data to contact you with newsletters, marketing or promotional materials and other information that may be of interest to you.</p>

                <h4>Usage Data</h4>
                <p>We may also collect information on how the Service is accessed and used. This Usage Data may include your IP address, browser type, browser version, pages visited, time and date of your visit, time spent on pages, unique device identifiers and diagnostic data.</p>

                <h4>Tracking &amp; Cookies Data</h4>
                <p>We use cookies and similar tracking technologies to track activity on our Service and hold certain information. You can instruct your browser to refuse all cookies or indicate when a cookie is being sent.</p>
                <p>Examples of cookies we use:</p>
                <ul>
                  <li><strong>Session Cookies.</strong> We use Session Cookies to operate our Service.</li>
                  <li><strong>Preference Cookies.</strong> We use Preference Cookies to remember your preferences and settings.</li>
                  <li><strong>Security Cookies.</strong> We use Security Cookies for security purposes.</li>
                  <li><strong>Advertising Cookies.</strong> Advertising Cookies are used to serve advertisements relevant to you.</li>
                </ul>

                <h4>Information that is passively or automatically collected</h4>
                <p>We and our third party service providers may use automated means to collect various types of information about you or your device used to access our Service, including browser type, network address, operating system, device settings, pages visited, device identifiers, location information, and content or ads accessed or clicked on.</p>

                <h2>Use of Data</h2>
                <p>Pikoya uses collected data to provide and maintain the Service, notify you about changes, allow interactive features, provide customer support, gather analysis, monitor usage, detect technical issues, and provide news, offers and information about similar services unless you have opted not to receive such information.</p>

                <h2>Legal Basis for Processing Personal Data under GDPR</h2>
                <p>If you are from the European Economic Area, Pikoya&apos;s legal basis for collecting and using personal information depends on the Personal Data collected and the context in which we collect it. Pikoya may process your Personal Data because we need to perform a contract with you, you have given permission, processing is in our legitimate interests, or to comply with law.</p>

                <h2>Retention of Data</h2>
                <p>Pikoya will retain your Personal Data only for as long as necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data as needed to comply with legal obligations, resolve disputes and enforce agreements and policies.</p>
                <p>Pikoya will also retain Usage Data for internal analysis purposes, generally for a shorter period unless needed for security, functionality improvement, or legal obligations.</p>

                <h2>Transfer of Data</h2>
                <p>Your information, including Personal Data, may be transferred to computers located outside your jurisdiction where data protection laws may differ. If you are outside Israel and provide information to us, please note that we transfer data to Israel and process it there.</p>
                <p>Your consent to this Privacy Policy followed by your submission of information represents your agreement to that transfer.</p>

                <h2>Disclosure of Data</h2>
                <h3>Business Transaction</h3>
                <p>If Pikoya is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data becomes subject to a different Privacy Policy.</p>
                <h3>Disclosure for Law Enforcement</h3>
                <p>Under certain circumstances, Pikoya may be required to disclose your Personal Data if required by law or in response to valid public authority requests.</p>
                <h3>Legal Requirements</h3>
                <p>Pikoya may disclose your Personal Data in good faith when necessary to comply with a legal obligation, protect rights or property, prevent wrongdoing, protect personal safety, or protect against legal liability.</p>

                <h2>Security of Data</h2>
                <p>The security of your data is important to us, but no method of transmission over the Internet or electronic storage is 100% secure. While we use commercially acceptable means to protect your Personal Data, we cannot guarantee absolute security.</p>

                <h2>Our Policy on Do Not Track Signals under CalOPPA</h2>
                <p>We do not support Do Not Track. You can enable or disable Do Not Track by visiting your browser preferences or settings page.</p>

                <h2>Your Data Protection Rights under GDPR</h2>
                <p>If you are a resident of the European Economic Area, you have certain data protection rights. Pikoya aims to take reasonable steps to allow you to correct, amend, delete or limit use of your Personal Data.</p>
                <ul>
                  <li><p><strong>The right to access, update or delete the information we have on you.</strong></p></li>
                  <li><p><strong>The right of rectification.</strong> You have the right to have inaccurate or incomplete information corrected.</p></li>
                  <li><p><strong>The right to object.</strong> You have the right to object to processing of your Personal Data.</p></li>
                  <li><p><strong>The right of restriction.</strong> You have the right to request restriction of processing.</p></li>
                  <li><p><strong>The right to data portability.</strong> You have the right to receive a copy of your data in a structured, machine-readable format.</p></li>
                  <li><p><strong>The right to withdraw consent.</strong> You have the right to withdraw consent at any time.</p></li>
                </ul>
                <p>Please note that we may ask you to verify your identity before responding to requests. You also have the right to complain to a Data Protection Authority.</p>

                <h2>Service Providers</h2>
                <p>We may employ third party companies and individuals to facilitate our Service, provide the Service on our behalf, perform Service-related services or assist us in analysing how our Service is used.</p>

                <h3>Analytics</h3>
                <p>We may use third-party Service Providers to monitor and analyse use of our Service.</p>
                <ul>
                  <li><p><strong>Google Analytics</strong></p><p>For more information, visit <a href="https://policies.google.com/privacy?hl=en">https://policies.google.com/privacy?hl=en</a></p></li>
                  <li><p><strong>Piwik or Matomo</strong></p><p><a href="https://matomo.org/privacy-policy">https://matomo.org/privacy-policy</a></p></li>
                  <li><p><strong>Clicky</strong></p><p><a href="https://clicky.com/terms">https://clicky.com/terms</a></p></li>
                  <li><p><strong>Statcounter</strong></p><p><a href="https://statcounter.com/about/legal/">https://statcounter.com/about/legal/</a></p></li>
                  <li><p><strong>Mixpanel</strong></p><p><a href="https://mixpanel.com/optout/">https://mixpanel.com/optout/</a> and <a href="https://mixpanel.com/terms/">https://mixpanel.com/terms/</a></p></li>
                </ul>

                <h3>Advertising</h3>
                <p>We may use third-party Service Providers to show advertisements to help support and maintain our Service.</p>
                <ul>
                  <li><p><strong>Google AdSense &amp; DoubleClick Cookie</strong></p><p><a href="http://www.google.com/ads/preferences/">http://www.google.com/ads/preferences/</a></p></li>
                  <li><p><strong>Bing Ads</strong></p><p><a href="https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized-ads">https://advertise.bingads.microsoft.com/en-us/resources/policies/personalized-ads</a></p></li>
                  <li><p><strong>StartApp</strong></p><p><a href="https://www.startapp.com/policy/privacy-policy/">https://www.startapp.com/policy/privacy-policy/</a></p></li>
                  <li><p><strong>AdButler</strong></p><p><a href="https://www.sparklit.com/agreements.spark?agreement=privacy">https://www.sparklit.com/agreements.spark?agreement=privacy</a></p></li>
                </ul>

                <h3>Behavioral Remarketing</h3>
                <p>Pikoya uses remarketing services to advertise on third party websites after you visited our Service.</p>
                <ul>
                  <li><p><strong>Google AdWords</strong></p><p><a href="http://www.google.com/settings/ads">http://www.google.com/settings/ads</a> and <a href="https://tools.google.com/dlpage/gaoptout">https://tools.google.com/dlpage/gaoptout</a></p></li>
                  <li><p><strong>Twitter</strong></p><p><a href="https://support.twitter.com/articles/20170405">https://support.twitter.com/articles/20170405</a> and <a href="https://twitter.com/privacy">https://twitter.com/privacy</a></p></li>
                  <li><p><strong>Facebook</strong></p><p><a href="https://www.facebook.com/help/164968693837950">https://www.facebook.com/help/164968693837950</a>, <a href="https://www.facebook.com/help/568137493302217">https://www.facebook.com/help/568137493302217</a>, <a href="http://www.aboutads.info/choices/">http://www.aboutads.info/choices/</a>, <a href="http://youradchoices.ca/">http://youradchoices.ca/</a>, <a href="http://www.youronlinechoices.eu/">http://www.youronlinechoices.eu/</a>, and <a href="https://www.facebook.com/privacy/explanation">https://www.facebook.com/privacy/explanation</a></p></li>
                  <li><p><strong>Pinterest</strong></p><p><a href="http://help.pinterest.com/en/articles/personalization-and-data">http://help.pinterest.com/en/articles/personalization-and-data</a> and <a href="https://about.pinterest.com/en/privacy-policy">https://about.pinterest.com/en/privacy-policy</a></p></li>
                  <li><p><strong>AdRoll</strong></p><p><a href="http://info.evidon.com/pub_info/573?v=1&amp;nt=1&amp;nw=false">http://info.evidon.com/pub_info/573?v=1&amp;nt=1&amp;nw=false</a> and <a href="http://www.adroll.com/about/privacy">http://www.adroll.com/about/privacy</a></p></li>
                  <li><p><strong>Perfect Audience</strong></p><p><a href="http://pixel.prfct.co/coo">http://pixel.prfct.co/coo</a>, <a href="http://ib.adnxs.com/optout">http://ib.adnxs.com/optout</a>, and <a href="https://www.perfectaudience.com/privacy/index.html">https://www.perfectaudience.com/privacy/index.html</a></p></li>
                  <li><p><strong>AppNexus</strong></p><p><a href="http://www.appnexus.com/platform-policy#choices">http://www.appnexus.com/platform-policy#choices</a> and <a href="http://www.appnexus.com/platform-policy/">http://www.appnexus.com/platform-policy/</a></p></li>
                </ul>

                <h2>Links to Other Sites</h2>
                <p>Our Service may contain links to other sites that are not operated by us. If you click a third party link, you will be directed to that site. We strongly advise you to review the Privacy Policy of every site you visit.</p>
                <p>We have no control over and assume no responsibility for content, privacy policies or practices of any third party sites or services.</p>

                <h2>Children&apos;s Privacy</h2>
                <p>Our Service does not address anyone under the age of 18. We do not knowingly collect personally identifiable information from anyone under 18. If we become aware that we have collected Personal Data from children without parental consent, we take steps to remove that information.</p>

                <h2>Changes to This Privacy Policy</h2>
                <p>We may update our Privacy Policy from time to time. We will notify you of changes by posting the new Privacy Policy on this page and updating the effective date.</p>

                <h2>Contact Us</h2>
                <p>If you have any questions about this Privacy Policy, please contact us:</p>
                <ul>
                  <li>By visiting this page on our website: <Link to="/contact">https://www.robloxgo.com/contact</Link></li>
                  <li>By calling us: +972-4-8583435</li>
                  <li>By sending us a letter: Derekh Yafo 30, Haifa, Israel</li>
                  <li>By sending us an email: support at pikoya.com</li>
                </ul>
              </span>
            </section>
          </div>
        </div>
      </div>
    </Layout>
  );
}
